version: '3'
services:
  db:
    image: postgres
    #container_name: db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      
  redis_db:
    image: 'redis:4.0-alpine'
    container_name: redis_db
    command: redis-server --requirepass yourpassword
    volumes:
      - 'redis:/data'
      
  faktory:
    image: contribsys/faktory
    container_name: faktory
    command: ./faktory -b :7419 -w :7420 -l debug
    ports:
      - "7419:7419"
      - "7420:7420"
      
  website:
    #container_name: website
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/text-track-service
    ports:
      - "3000:3000"
    depends_on:
      - db
      
volumes:
  redis:
  postgres: