default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: <%= ENV['DB_POOL'] %>
  timeout: <%= ENV['DB_TIMEOUT'] %>
  #pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_development
  pool: <%= ENV['DB_POOL'] %>
  timeout: <%= ENV['DB_TIMEOUT'] %>

test:
  <<: *default
  database: myapp_test
  pool: <%= ENV['DB_POOL'] %>
  timeout: <%= ENV['DB_TIMEOUT'] %>

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  pool: <%= ENV['DB_POOL'] %>
  timeout: <%= ENV['DB_TIMEOUT'] %>